version: '3.9'

services:
  teamspeak:
    image: teamspeak
    restart: always
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    volumes:
      - /usr/local/ts3server/data:/var/ts3server/
    environment:
      TS3SERVER_LICENSE: accept